[2025-01-29T16:30:46.687+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T16:30:46.721+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-04T12:00:00+00:00 [queued]>
[2025-01-29T16:30:46.740+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-04T12:00:00+00:00 [queued]>
[2025-01-29T16:30:46.775+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T16:30:46.795+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-01-04 12:00:00+00:00
[2025-01-29T16:30:46.807+0000] {standard_task_runner.py:72} INFO - Started process 1792 to run task
[2025-01-29T16:30:46.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-01-04T12:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpwq5ks5je']
[2025-01-29T16:30:46.815+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask taskBranch
[2025-01-29T16:30:46.893+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-04T12:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T16:30:47.111+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T12:00:00+00:00'
[2025-01-29T16:30:47.123+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T16:30:47.170+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-29T16:30:47.206+0000] {python.py:240} INFO - Done. Returned value was: taskC
[2025-01-29T16:30:47.211+0000] {branch.py:38} INFO - Branch into taskC
[2025-01-29T16:30:47.212+0000] {skipmixin.py:230} INFO - Following branch ('taskC',)
[2025-01-29T16:30:47.227+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1)]
[2025-01-29T16:30:47.315+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T16:30:47.324+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-01-04T12:00:00+00:00, execution_date=20250104T120000, start_date=20250129T163046, end_date=20250129T163047
[2025-01-29T16:30:47.355+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T16:30:47.368+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
