[2025-01-28T23:52:03.591+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T23:52:03.602+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2025-01-28T23:52:01.779071+00:00 [queued]>
[2025-01-28T23:52:03.609+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2025-01-28T23:52:01.779071+00:00 [queued]>
[2025-01-28T23:52:03.611+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-28T23:52:03.620+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_values_1> on 2025-01-28 23:52:01.779071+00:00
[2025-01-28T23:52:03.626+0000] {standard_task_runner.py:72} INFO - Started process 1171 to run task
[2025-01-28T23:52:03.628+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_1', 'manual__2025-01-28T23:52:01.779071+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmpmfcsi9iv']
[2025-01-28T23:52:03.630+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask insert_values_1
[2025-01-28T23:52:03.664+0000] {task_command.py:467} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_1 manual__2025-01-28T23:52:01.779071+00:00 [running]> on host 6b2a71fc0c6d
[2025-01-28T23:52:03.735+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='executing_sql_pipeline' AIRFLOW_CTX_TASK_ID='insert_values_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T23:52:01.779071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T23:52:01.779071+00:00'
[2025-01-28T23:52:03.736+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T23:52:03.745+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO users (id, name, age, is_active) VALUES
                (1, 'Julie', 30, false),
                (2, 'Peter', 55, true),
                (3, 'Emily', 37, false),
                (4, 'Katrina', 54, false),
                (5, 'Joseph', 27, true);
        
[2025-01-28T23:52:03.753+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-28T23:52:03.761+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-28T23:52:03.765+0000] {sql.py:553} INFO - Running statement: 
            INSERT INTO users (id, name, age, is_active) VALUES
                (1, 'Julie', 30, false),
                (2, 'Peter', 55, true),
                (3, 'Emily', 37, false),
                (4, 'Katrina', 54, false),
                (5, 'Joseph', 27, true);
        , parameters: None
[2025-01-28T23:52:03.767+0000] {sql.py:562} INFO - Rows affected: 5
[2025-01-28T23:52:03.778+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T23:52:03.779+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_1, run_id=manual__2025-01-28T23:52:01.779071+00:00, execution_date=20250128T235201, start_date=20250128T235203, end_date=20250128T235203
[2025-01-28T23:52:03.802+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T23:52:03.812+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
