[2025-02-04T23:13:55.296+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T23:13:55.315+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-04T23:13:55.323+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-04T23:13:55.324+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-04T23:13:55.338+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-02-01 00:00:00+00:00
[2025-02-04T23:13:55.343+0000] {standard_task_runner.py:72} INFO - Started process 91 to run task
[2025-02-04T23:13:55.346+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmp_89_4gn0']
[2025-02-04T23:13:55.348+0000] {standard_task_runner.py:105} INFO - Job 257: Subtask taskBranch
[2025-02-04T23:13:55.396+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-02-01T00:00:00+00:00 [running]> on host 099894fbbc67
[2025-02-04T23:13:55.479+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-02-04T23:13:55.481+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T23:13:55.504+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-04T23:13:55.517+0000] {python.py:240} INFO - Done. Returned value was: taskC
[2025-02-04T23:13:55.519+0000] {branch.py:38} INFO - Branch into taskC
[2025-02-04T23:13:55.521+0000] {skipmixin.py:230} INFO - Following branch ('taskC',)
[2025-02-04T23:13:55.533+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1)]
[2025-02-04T23:13:55.569+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T23:13:55.571+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250204T231355, end_date=20250204T231355
[2025-02-04T23:13:55.603+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T23:13:55.634+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-04T23:13:55.639+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
