[2025-01-29T17:13:58.062+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T17:13:58.104+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch backfill__2024-12-21T12:00:00+00:00 [queued]>
[2025-01-29T17:13:58.129+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch backfill__2024-12-21T12:00:00+00:00 [queued]>
[2025-01-29T17:13:58.134+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T17:13:58.158+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2024-12-21 12:00:00+00:00
[2025-01-29T17:13:58.177+0000] {standard_task_runner.py:72} INFO - Started process 3010 to run task
[2025-01-29T17:13:58.182+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'backfill__2024-12-21T12:00:00+00:00', '--job-id', '218', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpon8xb_qv']
[2025-01-29T17:13:58.187+0000] {standard_task_runner.py:105} INFO - Job 218: Subtask taskBranch
[2025-01-29T17:13:58.275+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch backfill__2024-12-21T12:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T17:13:58.426+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-12-21T12:00:00+00:00'
[2025-01-29T17:13:58.429+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T17:13:58.449+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-29T17:13:58.475+0000] {python.py:240} INFO - Done. Returned value was: taskC
[2025-01-29T17:13:58.478+0000] {branch.py:38} INFO - Branch into taskC
[2025-01-29T17:13:58.480+0000] {skipmixin.py:230} INFO - Following branch ('taskC',)
[2025-01-29T17:13:58.506+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1)]
[2025-01-29T17:13:58.556+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T17:13:58.566+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=backfill__2024-12-21T12:00:00+00:00, execution_date=20241221T120000, start_date=20250129T171358, end_date=20250129T171358
[2025-01-29T17:13:58.616+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T17:13:58.657+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-29T17:13:58.661+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
