[2025-01-29T16:30:49.652+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T16:30:49.701+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskC scheduled__2025-01-12T12:00:00+00:00 [queued]>
[2025-01-29T16:30:49.726+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskC scheduled__2025-01-12T12:00:00+00:00 [queued]>
[2025-01-29T16:30:49.729+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T16:30:49.760+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): taskC> on 2025-01-12 12:00:00+00:00
[2025-01-29T16:30:49.788+0000] {standard_task_runner.py:72} INFO - Started process 1875 to run task
[2025-01-29T16:30:49.800+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskC', 'scheduled__2025-01-12T12:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmphw8xklbd']
[2025-01-29T16:30:49.820+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask taskC
[2025-01-29T16:30:49.902+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskC scheduled__2025-01-12T12:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T16:30:50.036+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-12T12:00:00+00:00'
[2025-01-29T16:30:50.039+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T16:30:50.059+0000] {logging_mixin.py:190} INFO - TASK C has been executed!
[2025-01-29T16:30:50.060+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T16:30:50.077+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T16:30:50.080+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskC, run_id=scheduled__2025-01-12T12:00:00+00:00, execution_date=20250112T120000, start_date=20250129T163049, end_date=20250129T163050
[2025-01-29T16:30:50.135+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T16:30:50.169+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-29T16:30:50.173+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
